name: docker build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest image
        run: docker pull evanpurkhiser/venmo-lunchmoney-ai:latest
      - name: Build
        run: docker build --tag=evanpurkhiser/venmo-lunchmoney-ai:latest .
      - name: Publish
        run: |
          docker login --username=evanpurkhiser --password-stdin <<< "${{ secrets.DOCKER_HUB_TOKEN }}"
          docker push evanpurkhiser/venmo-lunchmoney-ai:latest
